package com.neytron.sshcommander.data

import com.jcraft.jsch.JSch
import com.jcraft.jsch.KeyPair
import java.io.ByteArrayOutputStream

actual object SshKeyUtils {
    actual fun generateKeyPair(type: String, bits: Int, passphrase: String?): Pair<String, String> {
        // Register BouncyCastle for broad algorithm support
        try {
            val bcProviderClass = Class.forName("org.bouncycastle.jce.provider.BouncyCastleProvider")
            if (java.security.Security.getProvider("BC") == null) {
                val bcProvider = bcProviderClass.getConstructor().newInstance() as java.security.Provider
                java.security.Security.addProvider(bcProvider)
            }
        } catch (e: Exception) {
            println("JSCH: [DEBUG] BC registration skipped: ${e.message}")
        }

        // Force JSch to recognize its own JCE implementations if defaults are missing
        try {
            JSch.setConfig("keypairgen.rsa", "com.jcraft.jsch.jce.KeyPairGenRSA")
            JSch.setConfig("keypairgen.dsa", "com.jcraft.jsch.jce.KeyPairGenDSA")
            JSch.setConfig("keypairgen.ecdsa", "com.jcraft.jsch.jce.KeyPairGenECDSA")
        } catch (e: Exception) {
            println("JSCH: [DEBUG] Failed to set global config: ${e.message}")
        }

        val jsch = JSch()
        
        // Use symbolic constants to avoid version-specific magic number issues
        val typeInt = when (type.uppercase()) {
            "RSA" -> KeyPair.RSA
            "ED25519" -> 5 // Const for Ed25519 in mwiede fork
            else -> KeyPair.RSA
        }
        
        val targetBits = if (typeInt == KeyPair.RSA) {
            if (bits < 2048) 4096 else bits
        } else if (typeInt == 5) {
            255
        } else {
            bits
        }

        println("JSCH: Generating $type key with $targetBits bits...")

        // Attempt generation with fallback
        var keyPair: KeyPair? = try {
            KeyPair.genKeyPair(jsch, typeInt, targetBits)
        } catch (e: Exception) {
            println("JSCH: [ERROR] Initial generation failed: ${e.message}")
            null
        }

        // Fallback to 2048 if 4096 failed for RSA
        if (keyPair == null && typeInt == KeyPair.RSA && targetBits > 2048) {
            println("JSCH: Falling back to 2048 bits for RSA...")
            keyPair = try {
                KeyPair.genKeyPair(jsch, typeInt, 2048)
            } catch (e: Exception) {
                println("JSCH: [ERROR] Fallback generation failed: ${e.message}")
                null
            }
        }
        
        if (keyPair == null) {
            throw Exception("Failed to generate key pair ($type). JSch returned null. Check your JVM crypto constraints.")
        }
        
        // Use reflection for setFormat(1) [1 = OPENSSH] to avoid compilation issues
        try {
            val setFormatMethod = keyPair.javaClass.getMethod("setFormat", Int::class.javaPrimitiveType ?: Int::class.java)
            setFormatMethod.invoke(keyPair, 1)
        } catch (e: Exception) {
            println("JSCH: [DEBUG] setFormat(OPENSSH) failed: ${e.message}")
        }
        
        val privateOut = ByteArrayOutputStream()
        val publicOut = ByteArrayOutputStream()
        
        try {
            if (!passphrase.isNullOrBlank()) {
                keyPair.writePrivateKey(privateOut, passphrase.toByteArray())
            } else {
                keyPair.writePrivateKey(privateOut)
            }
            
            keyPair.writePublicKey(publicOut, "Generated by SSH Commander")
        } catch (e: Exception) {
            keyPair.dispose()
            throw Exception("Failed to write key content to buffer: ${e.message}")
        }
        
        val priv = privateOut.toString()
        val pub = publicOut.toString()
        
        keyPair.dispose()
        
        return Pair(priv, pub)
    }
}
